In [1]:
import numpy as np

x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [2]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [3]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [4]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [5]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [7]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [8]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [9]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [10]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [11]:
org

array([  0,   1, 200,   3,   4])

In [12]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [13]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [14]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [15]:
org

array([0, 1, 2, 3, 4])

In [16]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [17]:
y = x.reshape(2, 3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
print(x.base)

None


In [19]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
y.base

array([0, 1, 2, 3, 4, 5])

In [21]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [22]:
c = z.copy()
print(c.base)

None


In [23]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [24]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [25]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [28]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b = a
b is a

True

In [31]:
print(id(a))
print(id(b))

1663255116368
1663255116368


In [32]:
print(a.base)
print(b.base)

None
None


In [33]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [34]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [35]:
print(id(a))
print(id(c))

1663255116368
1663255116560


In [36]:
print(c.base)

None


In [37]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [38]:
print(id(a))
print(id(v))

1663255116368
1663253605392


In [39]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [40]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [41]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [42]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [43]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [44]:
import numpy as np

a = array([3, 4, 5])
a

array([3, 4, 5])

In [45]:
b = 2
b

2

In [46]:
a + b

array([5, 6, 7])

In [47]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [48]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [49]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
y = arange(-1, 2)
y

#[[-1, 0, 1]
#[-1, 0, 1]
#[-1, 0, 1]]

array([-1,  0,  1])

In [51]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [52]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [53]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
y = arange(3, 10, 3).reshape(3, 1)
y

#[[3], [3], [3]
# [6], [6], [6]
# [9], [9], [9]]

array([[3],
       [6],
       [9]])

In [55]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [56]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [57]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [58]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [59]:
x / y

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [60]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [61]:
y = arange(1, 3)
y

array([1, 2])

In [62]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [63]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [64]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [65]:
np.newaxis is None

True

In [66]:
# 차수를 증감
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [67]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [68]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [69]:
a.shape

(4, 1)

In [70]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [71]:
b

array([1, 2, 3])

In [72]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [73]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [74]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [76]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [77]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [78]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [79]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [80]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [81]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [82]:
x[[0]]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [83]:
x[0, 1]

1

In [84]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [85]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [86]:
x[[0], [1]]

array([1])

In [87]:
# 0, 1행
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [88]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [89]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [90]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [91]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [92]:
# 첨자 [1, 2]과 [3, 2]에 해당하는 11과 26
x[[1, 3], [3, 2]]

array([11, 26])

In [93]:
# 1, 3행의 2열
x[[1, 3], [2]]

array([10, 26])

In [94]:
# 1, 3행의 2열
x[[1, 3], 2]

array([10, 26])

In [95]:
# 첨자 [1, 3]과 [3, 3]에 해당하는 11과 27
x[[1, 3], [3, 3]]

array([11, 27])

In [96]:
# 1, 3행의 3열
x[[1, 3], [3]]

array([11, 27])

In [97]:
from numpy import array

x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [98]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [99]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [100]:
x[array([0, 2, 4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [101]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [104]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [105]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [106]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [107]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [108]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [109]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [110]:
# 연습
np.r_[a, b, c]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [111]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [112]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [113]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [114]:
# 연습
np.c_[a, b]

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [115]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [116]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [117]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [118]:
# 연습
np.r_[np.arange(3), np.arange(10, 15)]

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [119]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [120]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [121]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [122]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [123]:
# 연습
np.c_[a, b]

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [124]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [125]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [126]:
x[np.newaxis]

array([[1, 2, 3]])

In [127]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [128]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [129]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [130]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [131]:
np.column_stack == np.hstack

False

In [132]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [134]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [135]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [136]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [137]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [138]:
np.row_stack == np.vstack

True

In [139]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [140]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [141]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [142]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [143]:
import numpy as np

x = np.arange(6).reshape(2, 3)
y

array([10, 20, 30])

In [144]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [145]:
np.concatenate([x, y])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [146]:
# 연습
print(np.vstack((x, y)))
print(np.row_stack((x, y)))
print(np.r_((x, y)))

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]
[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


TypeError: 'RClass' object is not callable

In [147]:
np.concatenate((x, y, z))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [148]:
np.concatenate((x, y), axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [149]:
np.concatenate((x, y, z), axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [150]:
# 연습
print(np.hstack((x, y, z)))
print(np.column_stack((x, y, z)))
print(np.c_((x, y, z)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [151]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [152]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [153]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [155]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
np.stack((a, b), axis=-2)

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [158]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [159]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [160]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [161]:
z = np.arange(20, 26).reshape(2, 3)
z 

array([[20, 21, 22],
       [23, 24, 25]])

In [162]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [163]:
ax0.shape

(3, 2, 3)

In [164]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [165]:
ax1.shape

(2, 3, 3)

In [166]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [167]:
ax2.shape

(2, 3, 3)

In [168]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [169]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [170]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [171]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [172]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [173]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [174]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [175]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [176]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [177]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [178]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [179]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [181]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [182]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [183]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [184]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [185]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [186]:
# 연습
np.c_[a, c]

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [187]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [189]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [190]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [192]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [193]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [194]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [195]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [196]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [197]:
#### 연습
np.r_['1, 2', [1, 2], [[10, 20]]]

array([[ 1,  2, 10, 20]])

In [198]:
#### 내 연습
np.r_[1, 2], [[1], [2]], [[10], [20]]

(array([1, 2]), [[1], [2]], [[10], [20]])

In [199]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [200]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [201]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [202]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [204]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [205]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [206]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [207]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [208]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [209]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [210]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [211]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [212]:
np.r_['0, 2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
np.r_['0, 3', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [214]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])
print(arr[:, None])
print(arr[np.newaxis, :])
print(arr[None, :])

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


In [215]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [216]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [217]:
np.expand_dims?

Signature:       np.expand_dims(a, axis)
Call signature:  np.expand_dims(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function expand_dims at 0x0000018341929E40>
File:            c:\users\109-1\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Expand the shape of an array.

Insert a new axis that will appear at the `axis` position in the expanded
array shape.

Parameters
----------
a : array_like
    Input array.
axis : int or tuple of ints
    Position in the expanded axes where the new axis (or axes) is placed.

    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as
        ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
        be treated as ``axis == 0``. This behavior is deprecated.

    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as
        described above are now forbidden and raise an `AxisError`.

Returns
-------
result : ndarray
   

In [218]:
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [219]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [220]:
np.expand_dims(arr, axis=(2, 0))

array([[[1],
        [2],
        [3]]])

In [221]:
np.expand_dims(arr, axis=(2, 0)).shape

(1, 3, 1)

In [222]:
np.expand_dims(arr, axis=(2, 1))

array([[[1]],

       [[2]],

       [[3]]])

In [223]:
np.expand_dims(arr, axis=(2, 1)).shape

(3, 1, 1)

In [224]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [225]:
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [226]:
np.expand_dims(np.array([1, 2, 3]), 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
np.expand_dims(np.array([1,2,3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [227]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [228]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]].shape

(6, 1, 1)

In [229]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [230]:
print(np.expand_dims(np.array([1,2,3]), axis=(0, 2)))
print(np.expand_dims(np.array([4,5,6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [231]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [232]:
print(np.expand_dims(np.array([1,2,3]), axis=(0, 1)))
print(np.expand_dims(np.array([4,5,6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [233]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]].shape

(2, 1, 3)

In [234]:
print(np.r_[[1,2,3], [4,5,6]])


np.r_['r', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [235]:
print(np.r_[[1,2,3], [4,5,6]])
np.r_['c', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [236]:
print(np.r_[[[1,2,3], [4,5,6]]])


np.r_['r', [[1,2,3], [4,5,6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [237]:
np.r_['c', [[1,2,3], [4,5,6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [238]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [239]:
print(a.shape)
print(b.shape)

(3,)
(3,)


In [240]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [241]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [242]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [243]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [244]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [245]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [246]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [248]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
np.r_['0, 2', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [250]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [252]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [253]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [254]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [255]:
np.r_['1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])